name: 'McNative Template Loader'
website: 'https://mcnative.org'
author: 'Pretronic'
depends: []
softdepend:
  - 'CloudNet-Bridge'
  - 'McNative'
  - 'ViaVersion'
  - 'CloudNetAPI'
  - 'Vault'
  - 'PlaceHolderApi'
  - 'ProtocolLib'
main: 'org.mcnative.loader.bootstrap.template.BukkitTemplateLoaderBootstrap'
version: '${project.version}'
